FirebaseError: Firebase Storage: User does not have permission to access 'exams'. (storage/unauthorized)
We have to make sure we are looking for exams in the correct location, exams are stored in firebase storage in a folder named "exams"